apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lold9g8yh-dotnet-basic
  janus-idp.io/tekton: lold9g8yh-dotnet-basic
  backstage.io/kubernetes-id: lold9g8yh-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lold9g8yh-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
