apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: lold9g8yh-dotnet-basic
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: lold9g8yh-dotnet-basic 
  name: lold9g8yh-dotnet-basic
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: lold9g8yh-dotnet-basic 
